WE-ARE-RACCOONS/postgraduate-back

src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringDetailResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringInfo.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/MentoringInfo.java
src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/user/application/dto/req/UserNickNameRequest.java
src/main/java/com/postgraduate/domain/user/application/dto/res/UserInfoResponse.java
src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
src/main/java/com/postgraduate/domain/user/presentation/UserController.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java

멘토링 관련 작업 + 대학생 마이페이지
엔티티 수정, 멘토링과 마이페이지의 분리로 인해 멘토링 작업 중단 이후 대학생 마이페이지 해당 작업
User 계좌, 은행 삭제 및 프로필 사진 추가
Senior 계좌, 은행, 교수님 추가
신청한 멘토링 조회 - 각 상태별
신청한 멘토링 상세 조회
유저 마이페이지 상단 노출용 정보 조회
유저 닉네임 수정 및 등록
요구사항 수정에 따른 테이블 수정해서 몇가지 정보 수정됨

RAC-83 feat : 멘토링 일부 및 대학생 마이페이지 작업

---

src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
src/main/java/com/postgraduate/domain/payment/presentation/constant/PaymentResponseCode.java
src/main/java/com/postgraduate/domain/review/presentation/constant/ReviewResponseCode.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
src/main/java/com/postgraduate/domain/user/presentation/UserController.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
src/main/java/com/postgraduate/global/dto/ErrorResponse.java
src/main/java/com/postgraduate/global/dto/ResponseDto.java
src/main/java/com/postgraduate/global/exception/ApplicationException.java
src/main/java/com/postgraduate/global/jwt/JwtProvider.java

- 사용자 정의 응답 코드 생성
- 토큰 예외 관련 부분 수정
모든 Entity에 맞춰 응답 코드를 만들고, 컨트롤러, `ResponseDto` 수정
`JwtProvider`에서 `validateToken`에서 예외를 잡아도 다른 처리를 하지 않아서 만료된 토큰도 모두 동작해서 우선 `IllegalArgumentException` 던지도록 변경
`parseClaim`에서 `ExpiredJwtException` 발생시 claim을 반환하도록 되어있는데, 해당 부분 삭제함
혹시 의도한 내용이라면 다시 되돌리겠음
HTTP 상태코드가 원래 정의되어 있고, 그 값 이외에 사용자 정의 코드를 사용하는 것이 맞는가 논의를 해볼 필요 있음
다만, ResponseDto 외에 기본으로 HTTP 상태코드는 전송이 되기 때문에 오히려 포함하면 2개의 동일한 상태코드가 가는 것이 아닌가 싶기도 함
ResponseDto에는 사용자 정의 코드를 포함시켜도 문제가 없을 듯 하여 우선 추가함

RAC-97 refactor : 사용자 정의 응답 코드 생성

---

src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/image/application/usecase/PreSignedUseCase.java
src/main/java/com/postgraduate/domain/image/exception/EmptyFileException.java
src/main/java/com/postgraduate/domain/image/exception/ImageException.java
src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseCode.java
src/main/java/com/postgraduate/domain/image/presentation/constant/ImageResponseMessage.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/senior/exception/NoneSeniorException.java
src/main/java/com/postgraduate/domain/senior/exception/SeniorException.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
src/main/java/com/postgraduate/domain/user/application/exception/NoneUserException.java
src/main/java/com/postgraduate/domain/user/application/exception/UserException.java
src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java

도메인 관련 예외 처리
Auth, Image, Senior, User 우선 구현된 부분에서 예외처리 추가
KakaoAccessUseCase에서 WebClient에서 발생하는 예외를 잡기 위해서 Try-Catch가 좀 많이 사용됐는데, 이 방법 말고 더 효율적인 방법이 있다면 추천해주세요!

RAC-129 feat : 도메인 관련 예외 처리

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorFieldResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorFieldResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Field.java
src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Postgradu.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/user/application/dto/res/UserPossibleResponse.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
src/main/java/com/postgraduate/domain/user/presentation/UserController.java

대학원생 분야 필터 추가
홈화면 대학원생 분야, 대학원 이용한 필터 기능 추가
- 분야 : 각각 분야 혹은 그 외의 다른 분야 필터링
- 대학원 : 중복 가능하게 대학원 검색 혹은 그 외 다른 대학원 + 전체 대학원 검색
마찬가지로 querydsl사용
senior의 Info값타입에 etcField, etcPostgradu추가 - 그 외인지 확인용 boolean타입

RAC-185 feat : 대학원생 분야 필터 추가

---

src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoTokenInfoResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java

회원 탈퇴 기본 로직 구현 -> 그 외에 회원 관련해서 해야할 수정은 아직 안함!
회원 탈퇴 요청시 기존 소셜과 연결을 끊어줌
-> 이후에 로그인을 원할 경우 다시 동의부터 해야함
User에 isDelete컬럼이 추가되었습니다 -> 탈퇴 상태 확인용! false는 정상 회원, true는 탈퇴 회원
단순히 끊기만 되어있는 부분이라 이외에 수정할 부분은 다른 브랜치에서 작업 예정입니다!
-> 좀 많을 것 같아서 이부분 먼저 pr날리고 다른 부분은 따로 처리하겠습니다~

RAC-230 feat : 회원 탈퇴 기본 로직 구현

---

src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/auth/application/dto/res/KakaoTokenInfoResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SelectOauth.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/constant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
src/main/java/com/postgraduate/domain/user/exception/DeletedUserException.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java

- 회원 탈퇴 기본 로직 구현
- 탈퇴 회원 고려 조회 로직 수정 및 일부 리펙토링
- 회원 탈퇴 요청시 기존 소셜과 연결을 끊어줌
-> 이후에 로그인을 원할 경우 다시 동의부터 해야함
- 기존의 for문을 Collection.forEach혹은 stream 활용으로 변경 (다만 가독성 고려하여 일부분 유지한 부분도 있음)
- 탈퇴 회원 토큰 발급X 예외 출력
- 삭제된 후배, 선배 조회 못하도록 수정 (상세조회, 전체 리스트 조회 등등)
멘토링 WAITING, EXPECTED, DONE에서 상대방이 탈퇴하면 해당 멘토링이 보임 - 안보이게 할 수 있지만,
어떤게 올바른 선택인지 모르겠어서 일단은 상세 조회만 막아놓음. 내가 진행한 내역은 볼 수 있는게 옳다고 생각함 (기획이 말하면 바꿀게요!)
User에 isDelete컬럼이 추가되었습니다 -> 탈퇴 상태 확인용! false는 정상 회원, true는 탈퇴 회원
탈퇴 유저에 대한 필터링을 하다 보니 메소드 길이가 너무 길어져서 querydsl등 다른 방식을 생각해볼 필요가 있을 것 같음
어짜피 n+1 문제 등등 고려한다면 이후에 querydsl을 사용할 가능성 또한 존재하기도 함

RAC-224 fix : 회원 탈퇴 로직 추가 및 기존 조회 수정

---

src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
src/main/java/com/postgraduate/domain/available/application/dto/req/AvailableCreateRequest.java
src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimeResponse.java
src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimesResponse.java
src/main/java/com/postgraduate/domain/available/application/mapper/AvailableMapper.java
src/main/java/com/postgraduate/domain/available/domain/entity/Available.java
src/main/java/com/postgraduate/domain/available/domain/repository/AvailableRepository.java
src/main/java/com/postgraduate/domain/available/domain/service/AvailableDeleteService.java
src/main/java/com/postgraduate/domain/available/domain/service/AvailableGetService.java
src/main/java/com/postgraduate/domain/available/domain/service/AvailableSaveService.java
src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageProfileResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java

기존 대학원생 가능 시간 로직 수정 -> 기획 수정에 따라서
- 대학원생 가능 시간에 대해 요일, 시작시간, 마감시간 가지는 테이블 생성
기존의 text로 받는 형식 삭제
- 위의 결과에 따라 기존의 시간 응답을 요일, 시작시간, 마감시간 정보를 가지는 리스트로 반환하도록 변환
- 기존의 멘토링에서 선배의 term을 가져와서 사용하고 있던 부분 mentoring자체의 term을 가지도록 수정
- 검색 결과 한줄 소개 삭제
멘토링의 경우 초기의 배포에서는 40분 고정이라 하였지만, 이후에는 멘토링마다 달라질 수 있는 점,
선배가 1시간 30분 가능하다고 멘토링이 무조건 1시간 30분이 되는 것은 아니기에 멘토링 자체의 term을 가지도록 생성
- 우선은 40분을 기본으로 가지도록 생성

RAC-232 fix : 기존 대학원생 가능 시간 정보 로직 수정

---

src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageUserAccountRequest.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java

계좌 포함 필수 아니도록 수정
- SeniorMyPageUserAccountRequest 계좌 관련 NotNull 제거
- 기존에 계좌 존재하지만 빈값 보낼 경우 예외 발생
- 기존에 계좌 존재하지 않을 경우 빈값 허용
로직에 문제 없는지 확인해주세요

RAC-242 fix : 선배 계정 설정시 계좌 포함 필수 유동적으로 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/req/UserChangeRequest.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorPossibleResponse.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
src/main/java/com/postgraduate/domain/wish/application/mapper/WishMapper.java
src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
src/test/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCaseTest.java

선후배 변경시 로직 변경
선배에서 후배 변경하는 경우에도 가능한지 확인
- 가능할 경우 후배로 변경 토큰 요청
- 불가능할 경우 후배 정보 추가 기입 및 토큰 발급
후배에서 선배로 변경하는 경우 로직 수정
- 가능할 경우 선배로 변경 토큰 요청
- 불가능할 경우 선배 정보 추가 기입 및 토큰 발급
각각의 API 분리 및 RefreshToken 로직 수정
- 토큰 재발급의 기본 로직은 user.getRole()을 통해 권한을 넣어주는데, 그렇게 할 경우 후배로 변경된 상태의 선배가 SENIOR로 들어가기 때문에 현재의 ROLE에 맞추도록 수정

RAC-248 feat : 선배가 후배로 변경하는 경우 로직 추가 및 기존 로직 변경

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
src/main/java/com/postgraduate/domain/user/presentation/UserController.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
src/main/java/com/postgraduate/global/logging/aop/LogTrace.java
src/main/java/com/postgraduate/global/logging/aop/LogUtils.java
src/main/java/com/postgraduate/global/logging/aop/TraceStatus.java
src/main/java/com/postgraduate/global/logging/dto/LogRequest.java

로그 저장 방식 변경
- 기존 Class record로 변경
- 필터 부분 로그 저장하도록 변경
- 하나의 API 같은 LogId사용하도록 수정
- 멘토링 자동 취소시 LocalDateTime으로 수정
- LocalDateTime으로 변경한 내용중 문제가 발생하는 부분이 있는지 한번 더 확인이 필요할 것 같습니다!
자동 취소에서 LocalDate를 사용하고 있어서 문제가 발생하고 있었습니다!

RAC-240 refactor : 로그 저장 방식 변경

---

src/main/java/com/postgraduate/domain/admin/application/dto/UserInfo.java
src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseMessage.java
src/main/java/com/postgraduate/domain/wish/application/mapper/WishMapper.java
src/main/java/com/postgraduate/domain/wish/domain/entity/Wish.java
src/main/java/com/postgraduate/domain/wish/domain/entity/constant/Status.java
src/main/java/com/postgraduate/domain/wish/domain/service/WishUpdateService.java
src/main/java/com/postgraduate/domain/wish/exception/MatchingNotReceiveException.java
src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseCode.java
src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseMessage.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java

+ 매칭 지원 기능을 구현했습니다.
+ `Wish` 엔티티에 매칭 지원 상태와 관련한 필드를 추가했습니다. (`status`)
+ 매칭 지원 완료하는 API를 구현했습니다.
관리자의 [후배회원] - [매칭지원완료] 칼럼은 
+ 빈칸
+ 대기중
+ 완료됨
으로 세 가지 입니다. `wish.status` 를 nullable 로 유지한 대신, '빈칸'의 경우 `wish.matchingReceive` 를 고려해 동의하지 않았다면 null 을 반환합니다. 혹시 더 나은 방법이 있다면 의견 주시면 감사하겠습니다 !

RAC-249 feat: 매칭 기능

---

src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/admin/application/usecase/UserManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/admin/presentation/AdminController.java
src/main/java/com/postgraduate/domain/admin/presentation/constant/AdminResponseMessage.java
src/main/java/com/postgraduate/domain/available/application/dto/res/AvailableTimesResponse.java
src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentUpdateService.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorSearchResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorProfileResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/wish/application/mapper/dto/res/WishResponse.java
src/main/java/com/postgraduate/domain/wish/domain/repository/WishRepository.java
src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java
src/main/java/com/postgraduate/domain/wish/exception/WishEmptyException.java
src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseCode.java
src/main/java/com/postgraduate/domain/wish/presentation/constant/WishResponseMessage.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java

+ 전체 점검 진행했습니다.
+ 충돌을 방지하기 위해 작업한 내용 먼저 머지 후, 노션에 점검사항 확인하면서 다른 브랜치에서 나머지 작업 하겠습니다.
+ 관리자에서 매칭 지원 정보를 기입하지 않은 [정보보기]가 아닌 [빈칸의 모달]을 보여주므로 지원 정보가 없다면 `null`을 반환하도록 했습니다.
+ 관리자에서 후배 멘토링 조회 시 선배 정보가 나오지 않는 오류를 해결했습니다.
+ 멘토링 취소 및 환불 기능을 추가했습니다. (환불의 경우 Payment 까지만)
+ 선배 상세 조회 시 로그인이 필요하므로 security에 권한 검사하도록 했습니다.
+ 멘토링 결제에서 멘토링 시간이 필요해 추가했습니다.

RAC-251 fix: 전체점검

---

src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/payment/exception/CertificationFailException.java
src/main/java/com/postgraduate/domain/payment/presentation/constant/PaymentResponseCode.java

환불 실패 커스텀 예외 수정
환불 실패 커스텀 예외 수정
- 예외 코드 (페이플 제공 예외 코드로 발생)

RAC-276 fix : 환불 실패 커스텀 예외 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringRenewalUseCase.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java

자동 갱신시 트랜잭션 롤백 설정 수정
- payment 조회시 DONE만 조회하도록 수정
- 자동 갱신시 예외 발생하는 경우 catch 후 수동으로 롤백 설정
예외를 발생시키면 자동으로 롤백이 되지만, 다음 반복이 수행되지 않기 때문에 catch 후 수동으로 롤백 설정하여 다음 반복을 수행할 수 있도록 수정

RAC-304 fix : 자동 갱신시 트랜잭션 롤백 설저 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringRenewalUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateService.java
src/main/java/com/postgraduate/domain/payment/application/mapper/PaymentMapper.java
src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCase.java
src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateServiceTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
src/test/java/com/postgraduate/domain/salary/presentation/SalaryControllerTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

Payment, Salary, Mentoring 관계 수정 및 결제 실패시 로직 수정
- Payment와 Salary 관계 제거
- Mentoring과 Salary 관계 추가
- Mentoring 완료시 Salary 업데이트 하도록 로직 수정
- 연관관계 수정에 따른 쿼리 수정 및 조회 로직 수정
- 결제 실패시 우선 정상 응답 후 멘토링 신청시 예외 출력하도록 변경
테이블 관계 수정에 따른 오류 유의
결제 실패에 대한 추가 확인 필요

RAC-304 fix : Payment, Salary, Mentoring 관계 수정 및 결제 실패시 로직 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/dto/res/ApplyingResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java

멘토링 신청시 계좌 여부 추가 반환
- 멘토링 신청시 계좌 존재하면 true, 없다면 false 반환
- 예외처리 try-catch에서 발생 예외 그대로 throw 이후 핸들러에서 처리하도록 수정

RAC-326 refactor : 멘토링 신청시 계좌 여부 추가 반환

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java

선후배 멘토링 상세보기 오류 수정
- 선배, 후배 멘토링 상세보기 권한 오류 수정
- 쿼리 수정 및 메소드 분리
- 기존 테스트 코드 수정
테스트 코드를 전체적으로 아예 손봐야 할 것 같음
이전에 테스트코드를 작성할 때 로직과 현재 로직이 다른 점이 많고, 메소드 자체가 삭제되고 추가된 것이 많아서 전체적인 변경이 필요할 것 같음!

RAC-326 fix : 선후배 멘토링 상세보기 오류 수정

---

src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioAuth.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioJuniorMessage.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioSeniorMessage.java

비즈뿌리오 토큰 발급 로직 수정
- Base64 encoding과정이 의도와 다르게 진행되는 부분 수정
- Redis에 토큰 저장 후 만료되는 경우에만 새롭게 토큰을 발급받아 사용하도록 수정

RAC-336 fix : 비즈뿌리오 토큰 발급 로직 수정

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java

정산 자동 생성 관련 오류 수정
- 다음 정산 생성시 기존 계좌 연결되지 않는 오류 수정
(동일한지 확인하는 비교문 문제)
- 선배 회원가입할 때 salary 2주치 생성
(목요일에 가입하는 경우 정산 자동 생성이 되지 않아 다음 정산이 비어버리는 경우 개선을 위해)
- 다음 정산 자동 생성시 이미 존재하는 경우 정산 생성하지 않고 넘어가도록 수정
(회원가입한 선배의 경우 이미 다음 정산을 가지고 있기 때문에 넘어가도록 작성)
정산 자동 생성의 로직에서 빈틈이 존재하는 것을 수정하기 위해 회원가입할 때 2주치 함께 생성하도록 수정함
이에 따라 발생할 수 있는 문제에 대한 관찰이 필요함

RAC-341 HotFix : 정산 자동 생성 관련 오류 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java
src/test/java/com/postgraduate/support/Resource.java

멘토링 완료건 조회시 완료일순 정렬
기존에 멘토링 생성일로 조회되는 것 완료건 조회시 완료일 순으로 수정
쿼리 기반이 아닌, 내부에서 sort를 사용하는 것으로 무엇이 나은지 추가적인 고려 필요

RAC-341 fix : 멘토링 완료건 조회시 완료일순 정렬

---

src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

선배 프로필 최초 작성시 seniorid반환 하도록 수정
senior/profile 에서도 seniorId반환 추가

RAC-347 HotFix : 선배 프로필 최초 작성시 seniorid반환 하도록 수정

---

src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioJuniorMessage.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioSend.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioSeniorMessage.java

알림톡 예외 발생시 기존 비즈니스 로직 영향 없도록 수정
알림톡 템플릿별 모든 메소드에 try/catch를 추가하여 로그 작성 후 무시하도록 수정
더 좋은 방법이 없는지 고민 필요

RAC-351 HotFix : 알림톡 예외 발생시 기존 비즈니스 로직 영향 없도록 수정

---

src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java

계좌 업데이트시 정산 동기화 오류 수정
- Before : 기존 계좌 존재하는 경우, 이번 정산만 조회하여 동기화 작업을 수행함
- After : 기존 계좌 존재하는 경우, 이번 정산일보다 정산일이 크거나 같은 정산을 모두 조회하여 모두 동기화 작업 수행
긴급 수정으로 관찰 필요 및 스프링 배치로 리팩토링시 고려 필요

RAC-364 HotFix : 계좌 업데이트시 정산 동기화 오류 수정

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/global/bizppurio/application/mapper/BizppurioMapper.java
src/main/java/com/postgraduate/global/bizppurio/application/usecase/BizppurioJuniorMessage.java
src/main/java/com/postgraduate/global/bizppurio/presantation/BizppurioController.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseTypeTest.java

후배 회원가입시 매칭 동의여부에 따라 알림톡 전송 기능 추가
- 후배 회원가입시 매칭 동의여부에 따라 알림톡 전송
- 기존 알림톡 수동 전송에서 매칭 대기 알림톡 전송 삭제

RAC-367 feat : 후배 회원가입시 매칭 동의여부에 따라 알림톡 전송 기능 추가

---

src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/global/slack/SlackCertificationMessage.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseTypeTest.java

선배 인증 요청 슬랙 웹훅 추가
선배 인증 요청시 슬랙 웹훅 발송

RAC-376 feat : 선배 인증 요청 슬랙 웹훅 추가

---

src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java

선배 분야 조회 및 검색 조회시 페이징 처리 최적화
- 커버링 인덱스 활용 선배 분야 조회 및 검색 조회시 페이징 처리 최적화
- totalInfo 길이 수정 -> 인덱스 설정을 위해
totalInfo -> Index 설정을 위해 text에서 varchar(500) 으로 변경
현재 사용자 기준, 가장 긴 totalIndex == 100자 -> 충분히 감당 가능 할 것으로 판단 하지만, 
필요에 따라 Index 최대 길이 수정 및 Text변경 가능

RAC-400 feat : 기존 페이징 처리 최적화

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyingUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyingUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/payment/usecase/PaymentManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java
src/test/java/com/postgraduate/support/Resource.java

선배 조회시 멘토링 진행 횟수 우선 정렬
- Senior 테이블에 mentoringHit 컬럼 추가 및 인덱스 설정
- 선배 조회시, mentoringHit 우선 정렬 후 조회수 정렬 및 ㄱㄴㄷ순 정렬
- 멘토링 신청 및 취소시 mentoringHit 업데이트 추가
Mentoring 의 senior count를 통해 order by를 설정하는 것 보다, mentoringHit 컬럼 추가 및 인덱스 처리를 통해 빠른 정렬 가능할 것이라 생각하여 Senior 테이블 수정하여 기능 추가함

RAC-403 fix : 선배 조회시 멘토링 진행 횟수 우선 정렬 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/req/TokenRequest.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/global/bizppurio/application/usecase/BizppurioSend.java

토큰 기반 로그인 추가
- 카카오 로그인시 accessToken 으로 전달 및 로그인 처리
- 테스트시 알림톡 전송 제외
이후 하나로 통합 필요
- [x] Label 설정했나요?

RAC-422 feat : 토큰 기반 로그인 추가

---

src/main/java/com/postgraduate/domain/auth/application/dto/req/RejoinRequest.java
src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
src/main/java/com/postgraduate/domain/auth/application/mapper/AuthMapper.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/user/quit/application/mapper/QuitMapper.java
src/main/java/com/postgraduate/domain/user/quit/application/usecase/QuitManageUseCase.java
src/main/java/com/postgraduate/domain/user/quit/domain/entity/Quit.java
src/main/java/com/postgraduate/domain/user/user/application/usecase/UserManageUseCase.java
src/main/resources/db/migration/V1_202408230342__modifyColumn.sql
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseTypeTest.java

탈퇴 로직 수정 및 이후 플로우 작성
- 탈퇴 사유 저장시 문자열로 변경
- 탈퇴시 소셜 연결 해제
- 탈퇴 회원 로그인시 isDelete 추가
- 회원 복구 API 추가
true -> 복구
false -> 소셜 해지
- 탈퇴 회원 추가로 인한 로그인 관련 응답 변경
-> 이후 로그인 로직 확정시 전체적으로 변경 가능

RAC-402 feat : 탈퇴 로직 수정 및 이후 플로우 작성

---

src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
src/main/java/com/postgraduate/global/slack/SlackErrorMessage.java
src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
src/test/java/com/postgraduate/support/ControllerTest.java

500에러 탐지시 슬랙 발송 추가
globalExceptionHandler에서 500 발생시 slack에 전파하도록 추가

RAC-449 feat : 500에러 탐지시 슬랙 발송 추가

---

src/main/java/com/postgraduate/domain/member/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/member/user/domain/service/UserSaveService.java
src/main/java/com/postgraduate/global/auth/login/application/usecase/oauth/SignUpUseCase.java

후배 가입(추가가입)시 토큰 발급 오류 해결
토큰 발급시, 후배 여부 확인 로직 변경에 의해 후배 유저 생성 후 후배 여부 조회 실패로 토큰 발급이 실패하는 문제 발생
-> 문제 발생 이전 기존 로직 : wishGetService에서 직접 user에 해당하는 wish 여부 확인하는 로직
-> 문제 발생 로직 : wishGetService를 사용하는 대신, User에 모든 책임을 지어준 후 user.isJunior를 호출하여 확인
-> 문제 발생 원인 : User를 막 생성한 직후, 트랜잭션 처리 이후 다시 조회하지 않는다면 User에는 Wish 객체가 따로 들어있지 않음
-> 문제 해결 : 두가지 방법 중 선택
1. 회원가입UseCase 사용 후 외부에서 UserGetService를 사용하여 트랜잭션이 완료된 이후 User를 조회 후 조회된 User 사용 (트랜잭션이 완료된 이후이기 때문에 DB에 존재하는 Wish를 함께 조회할 수 잇음
2. User에 Wish를 set하는 메소드 생성 후 User save시 `user.addWish(wish)` 를 사용 이렇게 하면, 트랜잭션이 완료된 상태가 아니더라도 wish가 들어간 객체가 되기 때문에 이어서 그대로 사용할 수 있음 -> 후배 회원을 생성하는 서비스의 메소드에 해당 코드를 추가하면 해결 가능
2번 방식 선택 (1번 선택시 트랜잭션 완료 이후, 조회하는 코드를 추가할 적절한 위치가 필요하며, 불필요한 쿼리 조회가 추가되기 때문에)

RAC-452 HotFix : 후배 가입(추가가입)시 토큰 발급 오류 해결

---

src/main/java/com/postgraduate/batch/scheduler/JobSchedulerConfig.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryRepository.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/java/com/postgraduate/global/auth/login/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/global/auth/login/util/ProfileUtils.java
src/main/java/com/postgraduate/global/slack/SlackErrorMessage.java
src/main/java/com/postgraduate/global/slack/SlackUtils.java
src/main/resources/templates/adminPayment.html

정산 배치 로직 수정
만약, 성공하지 못할 경우 최대 5회 재시도 및 5회 실패시 슬랙 웹훅 발송
```java
private void checkSalaryJobSuccess(JobParameters jobParameters) throws JobExecutionAlreadyRunningException, JobRestartException, JobInstanceAlreadyCompleteException, JobParametersInvalidException {
int retries = 0;
boolean success = false;
int seniorSize = seniorGetService.allSeniorId()
.size();
while (retries < MAX_RETRIES){
int salarySize = salaryGetService.findAllNext()
.size();
if (salarySize == seniorSize) {
success = true;
break;
}
jobLauncher.run(salaryJobWithAdmin, jobParameters);
}
if (!success) {
slackErrorMessage.sendSlackSalaryError();
}
}
```

RAC-451 fix : 정산 배치 로직 수정

---

.github/workflows/CD-develop.yml

CD workflow 수정
```shell
script: |
docker-compose -f /home/ec2-user/config/docker-compose.yml down
docker-compose -f /home/ec2-user/config/docker-compose.yml pull
docker-compose -f /home/ec2-user/config/docker-compose.yml up -d --force-recreate --build
```
이 부분에서 `docker-compose -f /home/ec2-user/config/docker-compose.yml pull` 와 `--force-recreate--build` 삭제 및 파일명 수정

RAC-478 fix : CD workflow 수정
