WE-ARE-RACCOONS/postgraduate-back

src/main/java/com/postgraduate/domain/auth/application/dto/AuthUserResponse.java
src/main/java/com/postgraduate/domain/auth/application/dto/JwtTokenResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/entity/constant/Role.java
src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
src/main/java/com/postgraduate/global/auth/AuthDetails.java
src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/jwt/JwtFilter.java
src/main/java/com/postgraduate/global/jwt/JwtProvider.java

JWT 로그인을 구현했습니다.
`@Builder.Default`로 초기화하도록 모든 엔티티 변경했습니다.
`user.point`의 경우 `int`타입으로 `@ColumnDefault("0")` 적용에 문제가 없어 그대로 진행하였습니다.
`SecurityConfig.java`에서 충돌이 예상됩니다.

RAC-85 feat: JWT 로그인

---

.github/workflows/CD-develop.yml

workflow 작성
workflow를 main에 만들어버려서 가죠옴
그냥 머지하겠슴당

RAC-66 feat : workflow 작성

---

src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringDetailResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/AppliedMentoringInfo.java
src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
src/main/java/com/postgraduate/domain/user/domain/entity/constant/Role.java
src/main/java/com/postgraduate/domain/user/presentation/UserController.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
src/main/java/com/postgraduate/global/config/redis/RedisRepository.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/jwt/JwtProvider.java

토큰 재발급 로직 수정 및 Cors 수정
- Redis 사용으로 변경
- Cors 수정
- JwtResponse에 Role추가 (Role에 SENIOR추가함)
시큐리티 및 토큰 수정으로 충돌 주의

RAC-83 fix : 토큰 관련 수정 및 Cors수정

---

src/main/java/com/postgraduate/global/config/security/SecurityConfig.java

RAC-83 fix : Cors 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
src/main/java/com/postgraduate/global/jwt/JwtFilter.java
src/main/java/com/postgraduate/global/jwt/JwtProvider.java

RefreshToken, 만료시간 추가
- RefreshToken받으면 Redis저장값과 직접 비교 후 재발급
- 반환시 만료시간 추가
- 만료시간 추가를 위해 Application.yml에 만료시간 추가 후 `@Value` 로 수정 
- -> 더 좋은 방식이 생각이 안나서 이 방식을 사용한 것으로 다른 아이디어도 좋습니다
- 하위 작업이 없어서 바로 Develop으로 머지할 예정

RAC-98 fix : RefreshToken 로직 수정 및 만료 시간 추가

---

src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java

RAC-102 fix: `GlobalExceptionHandler`에서 HttpStatus 제외

---

src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/exception/KakaoCodeException.java
src/main/java/com/postgraduate/domain/auth/exception/KakaoException.java
src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/user/application/exception/NotFoundUserException.java
src/main/java/com/postgraduate/domain/user/domain/service/UserGetService.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseCode.java
src/main/java/com/postgraduate/domain/user/presentation/constant/UserResponseMessage.java
src/main/java/com/postgraduate/global/auth/AuthDetailsService.java
src/main/java/com/postgraduate/global/config/security/util/SecurityUtils.java
src/main/java/com/postgraduate/global/jwt/JwtFilter.java
src/main/java/com/postgraduate/global/jwt/JwtProvider.java
src/main/java/com/postgraduate/global/jwt/constant/JwtResponseCode.java
src/main/java/com/postgraduate/global/jwt/constant/JwtResponseMessage.java
src/main/java/com/postgraduate/global/jwt/exception/InvalidRefreshTokenException.java
src/main/java/com/postgraduate/global/jwt/exception/InvalidTokenException.java
src/main/java/com/postgraduate/global/jwt/exception/JwtException.java
src/main/java/com/postgraduate/global/jwt/exception/NoneRefreshTokenException.java
src/main/java/com/postgraduate/global/jwt/exception/TokenExpiredException.java
src/main/java/com/postgraduate/global/logging/dto/LogRequest.java
src/test/java/com/postgraduate/domain/auth/application/usecase/kakao/KakaoSignInUseCaseTest.java

Global 패키지 관련 예외 처리
카카오 로그인시 발생하는 문제 해결 및 코드 예외 추가
토큰 예외 생성
토큰 관련 예외 처리 -> 필터에서 발생하는 예외 추가로 처리
Filter에서 예외가 발생하게 되면 스프링으로 접근하기 이전에 끝나기 때문에 AOP가 동작하지 못하기에 수동으로 log등록 
또한 ControllerHandler에서 예외 처리가 안되기 때문에 수동으로 응답 생성

RAC-130 feat : Global 부분 예외 처리

---

src/main/java/com/postgraduate/domain/auth/exception/PermissionDeniedException.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java

응답 코드 수정
회원가입 추가 진행 필요가 EX로 나와서 수정
이 부분은 바로 머지하겠슴다

RAC-136 fix : 응답 코드 수정

---

src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java

빌드 실패 수정
빌드 실패에 따른 수정 -> 빠른 merge필요
바로 머지하겠습니다

RAC-146 fix : 리팩토링에 의한 테스트코드 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/req/SignUpRequest.java
src/main/java/com/postgraduate/domain/user/application/dto/req/UserHopeRequest.java
src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
src/main/java/com/postgraduate/domain/user/domain/entity/Hope.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCaseTest.java

회원가입 부분 수정
회원가입시 매칭 여부 입력 추가
빠른 반영이 필요해서 다른 PR보다 먼저 적용시키도록 하겠습니다!

RAC-146 refactor : 회원가입시 매칭 희망 여부 추가

---

src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java

빌드 실패 해결
테스트 코드 주석처리
빌드가 안돼서 테스트 코드 주석처리함

RAC-153 fix : 수정에 의한 테스트 빌드 실패 해결

---

src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/config/security/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/filter/CustomAuthenticationEntryPoint.java

Security 예외 처리
+ 인증 예외 핸들러를 추가했습니다.
+ 인증 실패 코드, 메시지 추가했습니다.
+ 인가 예외 핸들러를 추가했습니다.
.

RAC-128 feat: Security 예외 처리

---

src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseCode.java
src/main/java/com/postgraduate/domain/auth/presentation/contant/AuthResponseMessage.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/config/security/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/filter/CustomAuthenticationEntryPoint.java

선배 상세 프로필 조회 기능
+ 후배가 조회하는 선배 상세 프로필 조회 기능을 추가했습니다.
+ 프로필을 등록하지 않은 선배는 조회할 수 없습니다.
+ 선배 리스트는 세부 필터가 나오지 않아 이후에 작업하겠습니다.

RAC-156 feat: 선배 상세 프로필

---

src/main/java/com/postgraduate/PostgraduateApplication.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java

멘토링 자동 취소
@Scheduled사용
너무 사소한 일에 배치를 도입하면 오히려 오버헤드가 증가하기도 하고 유지보수하기에 힘들어지는 장점 없고 단점만 있다고 해서
그냥 간단하게 구현함

RAC-158 feat : 매일 자정 기간 지난 멘토링 신청 자동 취소

---

src/main/java/com/postgraduate/domain/account/domain/entity/Account.java
src/main/java/com/postgraduate/domain/account/domain/service/AccountUpdateService.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageProfileRequest.java
src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorMyPageUserAccountRequest.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageProfileResponse.java
src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageUserAccountResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
src/main/java/com/postgraduate/domain/senior/exception/NoneAccountException.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseCode.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/JwtFilter.java

요구사항 변경점 적용 + 기존 오류 해결 및 로그 추가
- 대학원생 마이페이지 계정 설정
- 대학원생 마이페이지 프로필 수정
-> 두개로 분리
---
- 대학원생 멘토링 확정시 계좌 등록여부 확인
- 대학원생 상세보기시 조회수 업데이트 오류 해결
---
- 필터 패키지 위치 변경 및 토큰 인증시 로그 추가
구현시 실제 동작 여부 테스트해주세요
- 대학원생 상세보기 조회수 업데이트가 안되는 오류가 있었어요
---
record를 도입하려 하는데, 올려준 글도 읽어보고 적절한 사용 범위를 고려해봐요

RAC-169 fix : 변경된 요구사항 적용

---

src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java

+ 데이터 타입을 변경했습니다.
+ topic, question : 500자
+ info, target: 1000자
+ certification: 1000자
+ db에 반영해야 합니다

RAC-222 fix: 데이터 타입 변경

---

src/main/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCase.java
src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/global/config/s3/Default.java

임시 기본 이미지 설정
프론트 요청사항
- 임시 기본 이미지 설정
이후에 기본 이미지 받으면 수정 예정 및 바로 머지함

RAC-246 fix : 기본 이미지 설정

---

src/test/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCaseTest.java

build 실패 해결
테스트 실패로 인한 빌드 실패 해결
바로 머지함

RAC-246 test : 기본 이미지 변경 테스트 수정

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignOutUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
src/test/java/com/postgraduate/domain/account/domain/service/AccountUpdateServiceTest.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetServiceTest.java
src/test/java/com/postgraduate/domain/mentoring/domain/service/MentoringUpdateServiceTest.java
src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java
src/test/java/com/postgraduate/domain/salary/domain/service/SalaryGetServiceTest.java
src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorGetServiceTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java
src/test/java/com/postgraduate/domain/user/domain/service/UserGetServiceTest.java
src/test/java/com/postgraduate/domain/user/domain/service/UserUpdateServiceTest.java
src/test/java/com/postgraduate/domain/wish/domain/service/WishGetServiceTest.java

service 패키지 테스트 코드 작성
service의 get, update 부분 테스트 코드 작성
작성 도중 UserUpdateService만 내부에서 userId를 통해 조회를 하고 업데이트를 진행하고 있고 그 외에는 객체 자체를 받고 있어서
UserUpdateService 또한 User객체를 파라미터로 받도록 수정
그외에 회원가입시 불필요한 쿼리를 날리는 부분이 있어 삭제했습니다~!

RAC-238 test : 서비스 테스트 코드 작성

---

src/main/java/com/postgraduate/domain/account/domain/entity/Account.java
src/main/java/com/postgraduate/domain/available/domain/entity/Available.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
src/main/java/com/postgraduate/domain/refuse/domain/entity/Refuse.java
src/main/java/com/postgraduate/domain/review/domain/entity/Review.java
src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/wish/domain/entity/Wish.java

fetch LAZY 설정
fetch LAZY 설정
연관 관계 모두 LAZY 설정 하였는데, 다른 의견 있다면 말해주세요

RAC-264 refactor : fetch LAZY 설정

---

.github/workflows/CI-develop.yml
Dockerfile

배포 과정 수정
- PR올릴 때 CI동작하도록 하여 미리 빌드를 하고 에러를 잡을 수 있도록 구현
- JDK 경량화 버전 사용하여 이미지 최적화 시도
- [x] Label 설정했나요?

RAC-274 deploy : CI/CD 분리 및 jdk 경량화 버전 사용

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorPossibleResponse.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java

socialId 추가
`/senior/me/role` 여기서 socialId 반환 추가했습니다

RAC-288 fix : socialId 추가(프론트 요구사항)

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/AllSeniorIdResponse.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorRepository.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/senior/presentation/constant/SeniorResponseMessage.java

seniorId 리스트 조회 추가
프론트 요청사항 - seniorId 리스트 조회 (user탈퇴 X)

RAC-288 feat : seniorId 리스트 조회 추가

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java

개발용 소셜 로그인 추가
개발용 소셜 로그인 추가 (개발 전용)

RAC-288 feat : 개발용 소셜 로그인 추가

---

.github/workflows/CD-develop.yml
.github/workflows/CI-develop.yml
src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
src/main/java/com/postgraduate/global/logging/aop/LogTrace.java
src/main/java/com/postgraduate/global/mq/producer/MessageProducer.java
src/main/resources/logback-spring.xml

logback 추가
30일 저장기간의 logback 추가
서버에 올리고 테스트해야하는 내용이 좀 있어서 우선 머지하고 테스트 하겠습니다!

RAC-292 feat : log 파일 생성

---

src/main/resources/logback-spring.xml

fix : logback 수정
오류 사항이 있어서 추가로 올립니다
이것도 바로 merge해서 확인하겠습니다~ 로깅용이라서 로직은 안건드렸습니다!

RAC-292 fix : logback 수정

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorDetailResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

선배 상세조회 본인 여부 확인 추가
senior/{seniorId} 에서 본인 여부 확인 추가 (isMine 추가)
User클래스에 isEqual추가하여 User같은지 여부 확인
테스트 코드 1개 추가
**빠르게 작성한 로직으로 체크 필요!**

RAC-288 feat : 선배 상세조회 본인 여부 확인 추가

---

src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java

비로그인 상태 선배 상세조회 가능하도록 수정
SecurityConfig `senior/{seniorId}` 접근 제한 해제
User의 isEqual메소드 수정

RAC-304 fix : 비로그인 상태 선배 상세조회 가능하도록 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java

멘토링 기본 시간 조정, 확인용 로그 추가(예외 확인용)
멘토링 30분으로 변경, 본인의 멘토링 확인시 권한 실패발생 -> 확인용 로그 추가
확인이 필요하기 때문에 빠른 머지를 한 이후 리뷰를 부탁드립니다!

RAC-304 fix : 멘토링 기본 시간 조정 및 확인용 로그 추가

---

build.gradle

jacoco file위치 수정
test 보고서 파일 위치 수정

RAC-306 fix : jacoco file위치 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCase.java
src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/payment/domain/entity/Payment.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyUseCaseTest.java
src/test/java/com/postgraduate/domain/payment/domain/service/PaymentGetServiceTest.java

결제 처리 API 추가
- 결제 처리 API 리다이렉트 추가 및 개발용 API 추가

RAC-282  feat : 결제 처리 API 추가

---

src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java

결제시 결제 실패외 모든 예외 무시
예외 무시를 하지 않는 경우 결제 내역이 DB에 저장되지 않기 때문에 무시 후 다음 단계에서 각각 처리

RAC-276 fix : 모든 Exception 처리

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseCode.java
src/main/java/com/postgraduate/domain/mentoring/presentation/constant/MentoringResponseMessage.java
src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
src/main/java/com/postgraduate/global/logging/service/LogService.java
src/main/java/com/postgraduate/global/slack/SlackErrorMessage.java
src/main/java/com/postgraduate/global/slack/SlackLogErrorMessage.java
src/main/java/com/postgraduate/global/slack/SlackSalaryMessage.java
src/main/java/com/postgraduate/global/slack/SlackUtils.java
src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/salary/presentation/SalaryControllerTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java

기존 자동 갱신 로직 수정 및 슬랙 메시지 전송
- 자동 취소 및 완료 실패시 슬랙 메시지 전송
- 자동 취소 및 완료 실패시 실패 항목 제외 진행하지 못하는 부분 해결
- 멘토링 신청 실패시 실패 메시지 전송 (자동 환불 진행)
추가적으로 점검 필요

RAC-311 fix : 기존 자동 갱신 로직 수정 및 슬랙 메시지 전송

---

src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java

SalaryDate 계산 수정
- 매달 10일의 다음 정산일 다음달 10일로 수정

RAC-311 fix : SalaryDate 계산 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java

RAC-304 fix : 거절시 환불

---

.github/workflows/CD-prod.yml
.github/workflows/CI-prod.yml

github ip aws sg추가
prod부분 ci/cd workflow 수정

RAC-67 deploy : github ip aws sg추가

---

.github/workflows/CI-prod.yml

RAC-67 fix : workflow수정

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java

RAC-67 refactor : 오류 로그 처리

---

src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java
src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
src/main/java/com/postgraduate/global/logging/service/LogService.java
src/main/resources/logback-spring.xml

error로그 추가
error로그 추가 및 로그 2주 보관으로 설정

RAC-315 refactor : error로그 추가

---

.github/workflows/CD-prod.yml
.github/workflows/CI-prod.yml
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/global/config/security/SecurityConfig.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/JwtFilter.java
src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java

RAC-315 refactor : ERROR 로그 추가

---

src/main/java/com/postgraduate/domain/admin/application/usecase/MentoringManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentRepository.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java

Senior 멘토링 거절시 환불 오류 수정
Payment 조회 오류 수정 (user사용X)

RAC-304 fix : Senior 멘토링 거절시 환불 오류 수정

---

.github/workflows/CD-develop.yml
.github/workflows/CD-prod.yml
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java

Salary 조회 오류 수정
Salary 조회시 완료안된 멘토링 포함되는 오류 해결

RAC-304 fix : Salary 조회 오류 수정

---

src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java

senior 프로필 업데이트 오류 수정
senior 프로필 업데이트 오류 수정 (업데이트시 분야 기타 여부 처리 오류)

RAC-304 fix : senior 프로필 업데이트 오류 수정

---

src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/resources/logback-spring.xml

logback 수정
logback 수정 (highlight 적용 및 불필요한 내용 제거)

RAC-304 fix : logback 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthResponse.java
src/main/java/com/postgraduate/domain/auth/application/dto/res/AuthUserResponse.java
src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/CheckIsMyMentoringUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java
src/main/java/com/postgraduate/domain/user/application/mapper/UserMapper.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java

qa 반영
기본 프로필 사진 수정 및 와일드 카드 삭제
로그 레벨 수정

RAC-304 fix : qa 반영

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java

RAC-304 fix : 자동 갱신 로직 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Postgradu.java

선배 회원가입시 학교 분류 수정
- 선배 회원가입시 학교 분류 수정 - 서울대 x -> 서울대학교
- 로그 추가

RAC-304 fix : 선배 회원가입시 학교 분류 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Postgradu.java

RAC-304 deploy : 운영 반영

---

src/main/java/com/postgraduate/domain/payment/application/mapper/PaymentMapper.java
src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java

결제 실패시 환불 진행 추가
- 결제 실패시 환불 로직 추가
- 불완전 payment 생성 후 환불 구현
- Salary 조회 수정
불완전 payment 생성 후 환불 구현 이 부분에 대한 고민 필요

RAC-304 fix : 결제 실패시 환불 진행 추가

---

src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
src/main/java/com/postgraduate/global/dto/ErrorResponse.java
src/main/java/com/postgraduate/global/exception/ApplicationException.java
src/main/java/com/postgraduate/global/exception/GlobalExceptionHandler.java
src/main/java/com/postgraduate/global/logging/aop/LogAspect.java
src/main/java/com/postgraduate/global/logging/aop/LogTrace.java

RAC-304 fix : 에러 코드 변경

---

src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java

RAC-304 fix : QA용 수정 원복

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepository.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringRepository.java

멘토링 갱신 수정
- mentoring update시 트랜잭션 내부에 속하도록 수정
- 자동 완료 갱신 fetchJoin 사용하도록 수정

RAC-304 fix : 멘토링 갱신 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java

RAC-304 fix : 자동 갱신시 update 오류 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringRenewalUseCase.java

자동 갱신 클래스 분리
- 자동 갱신 클래스 분리
- 같은 클래스의 내부 메소드 호출시 트랜잭션 적용되지 않는 이유로 클래스 분리

RAC-304 fix : 자동 갱신 클래스 분리

---

src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringRenewalUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java

RAC-304 deploy : 운영 적용

---

src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

나의 정보 조회시 인증 이전에도 조회 가능하도록 수정
인증 이전 프로필 조회시 조회 안되는 오류 수정

RAC-304 fix : 나의 정보 조회시 인증 이전에도 조회 가능하도록 수정

---

src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

프로필 미완성 선배 조회 수정
프로필 미완성 선배 조회되는 오류 수정

RAC-304 fix : 프로필 미완성 선배 조회 수정

---

src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java

토큰 없이 선배 상세조회 안되는 오류 해결
토큰 없이 선배 상세조회 안되는 오류 해결
- 로직 수정
HotFIx로 불안정할 수 있음!! 추가적인 검토 필요

RAC-304 hotFix : 토큰 없이 선배 상세조회 안되는 오류 해결

---

src/main/java/com/postgraduate/domain/payment/application/usecase/PaymentManageUseCase.java
src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java

Payple결제 취소시 리다이렉트 수정
결제 취소 및 실패시 리다이렉트 하도록 수정

RAC-304 fix : Payple결제 취소시 리다이렉트 수정

---

src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryManageUseCase.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java

정산 단위 주단위로 변경
매주 목요일 정산 변경
-> 일 ~ 토 이번 정산 (담주 목요일)
-> 돌아오는 일요일 부터는 다음 정산

RAC-322 fix : 정산 단위 주단위로 변경

---

src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/java/com/postgraduate/domain/salary/util/SalaryUtil.java

RAC-322 deploy : 운영 반영

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseCase.java

RAC-304 deploy : 기본 프로필 변경

---

src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCaseTest.java

후배회원 선배 조회 안되는 오류 해결
`checkIsMine` 메소드를 무조건 수행하여 일반 후배 회원의 경우 발생하는 문제 해결

RAC-325 HotFix : 후배회원 선배 조회 안되는 오류 해결

---

src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/service/MentoringGetService.java

결제 조회 오류 해결
- 결제건 멘토링 존재하지 않을 경우 결제창 오류 해결

RAC-325 fix: 결제 조회 오류 해결

---

src/main/java/com/postgraduate/domain/adminssr/application/dto/res/CertificationDetailsResponse.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/MentoringInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/MentoringManageResponse.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/MentoringWithPaymentResponse.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/PaymentInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/SalaryDetailsResponse.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/SalaryInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/SalaryInfoWithOutId.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/SeniorInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/UnSettledSalaryInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/UserInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/UserMentoringInfo.java
src/main/java/com/postgraduate/domain/adminssr/application/dto/res/WishResponse.java
src/main/java/com/postgraduate/domain/adminssr/application/mapper/AdminSsrMapper.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminMentoringUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminPaymentUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSalaryUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSeniorUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminUserUseCase.java
src/main/java/com/postgraduate/domain/adminssr/presentation/AdminWithThymeLeafController.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/resources/templates/adminMain.html
src/main/resources/templates/adminSenior.html
src/main/resources/templates/seniorMentoring.html
src/main/resources/templates/seniorSalary.html
src/main/resources/templates/unSettledSalary.html
src/main/resources/templates/userMentoring.html
src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoWithOutIdUseCaseTest.java

관리자 페이지 내용 수정 및 패키지 변경
- 계획된 관리자 페이지를 개발 용이성을 고려하여 수정
- 추가로, 부족한 정보 노출을 보완
- 임시 관리자 패키지와 본래의 관리자 패키지 구분
html코드가 더럽다
단순 패키지 분리를 하려고 하다보니 같은 내용을 가진 패키지가 두개 생겨 중복이 굉장히 많다.
다만, 의도한 상황이니 넘어가도록 하겠다!

RAC-325 fix : 관리자 페이지 내용 수정 및 패키지 변경

---

src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminPaymentUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSeniorUseCase.java
src/main/java/com/postgraduate/domain/adminssr/presentation/AdminWithThymeLeafController.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepository.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/payment/domain/service/PaymentGetService.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/main/java/com/postgraduate/domain/wish/domain/repository/WishDslRepository.java
src/main/java/com/postgraduate/domain/wish/domain/repository/WishDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/wish/domain/service/WishGetService.java

멘토링 완료 이후 취소시, 선배 정산 금액 차감 문제 해결
- 멘토링 완료 이후 취소하는 경우 선배 정산 금액 차감하도록 수정
- 조회 쿼리문 수정하여 좀 더 효율적으로 변경

RAC-325 fix : 멘토링 완료 이후 취소시, 선배 정산 금액 차감 문제 해결

---

src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminPaymentUseCase.java
src/main/resources/templates/adminMain.html
src/main/resources/templates/adminPayment.html
src/main/resources/templates/adminSenior.html
src/main/resources/templates/adminUser.html
src/main/resources/templates/paymentMentoring.html
src/main/resources/templates/seniorCertification.html
src/main/resources/templates/seniorMentoring.html
src/main/resources/templates/seniorSalary.html
src/main/resources/templates/unSettledSalary.html
src/main/resources/templates/userMentoring.html
src/main/resources/templates/userWish.html

기존 스크립트 중복 코드 삭제
HTML 내부 스크립트 중복 코드 삭제

RAC-325 refactor : 기존 스크립트 중복 코드 삭제

---

src/main/java/com/postgraduate/domain/admin/application/mapper/AdminMapper.java
src/main/java/com/postgraduate/domain/admin/application/usecase/SalaryManageByAdminUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/mapper/AdminSsrMapper.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSalaryUseCase.java
src/main/java/com/postgraduate/domain/adminssr/presentation/AdminWithThymeLeafController.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCase.java
src/main/java/com/postgraduate/domain/mentoring/domain/entity/Mentoring.java
src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
src/main/java/com/postgraduate/domain/salary/domain/entity/Salary.java
src/main/java/com/postgraduate/domain/salary/domain/entity/SalaryAccount.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepository.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryGetService.java
src/main/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateService.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepository.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorGetService.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoWithOutIdUseCaseTest.java
src/test/java/com/postgraduate/domain/salary/domain/service/SalaryUpdateServiceTest.java
src/test/java/com/postgraduate/domain/salary/presentation/SalaryControllerTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

도메인 집중적으로 로직 수정 및 테스트 코드 수정
- 정산 계좌 값타입으로 분리
- 수정사항 조회 로직 반영 및 불필요한 쿼리 제거
- 기존 테스트 코드 수정사항 반영

RAC-326 refactor : 도메인 집중적으로 로직 수정 및 테스트 코드 수정

---

src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java

테스트시 슬랙 메시지 전송 안하도록 수정
테스트시 슬랙 메시지 보내는 부분 수정

RAC-326 HotFix : 테스트시 슬랙 메시지 전송 안하도록 수정

---

src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java

관리자 페이지 정산관리 0원은 제외하도록 수정
관리자 페이지 정산관리 0원은 제외하도록 수정
- [] 리뷰어 설정했나요?

RAC-326 HotFix : 관리자 페이지 정산관리 0원은 제외하도록 수정

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorSearchResponse.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java

선배리스트 조회시 교수님 추가
리스트마다 professor 가 추가됨

RAC-326 HotFix : 선배리스트 조회시 교수님 추가

---

src/main/java/com/postgraduate/domain/available/domain/repository/AvailableDslRepository.java
src/main/java/com/postgraduate/domain/available/domain/repository/AvailableDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/available/domain/service/AvailableGetService.java
src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/payment/domain/repository/PaymentDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/salary/domain/repository/SalaryDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/wish/domain/repository/WishDslRepositoryImpl.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java

선배 자신의 시간 조회시 인증여부 상관없이 조회 가능하도록 변경
선배가 자신의 프로필 조회시 인증이 되지 않은 선배의 경우 시간이 조회되지 않는 문제 수정

RAC-326 HotFix : 선배 자신의 시간 조회시 인증여부 상관없이 조회 가능하도록 변경

---

src/main/java/com/postgraduate/global/slack/SlackPaymentMessage.java
src/main/java/com/postgraduate/global/slack/SlackSignUpMessage.java

슬랙 메시지 내용 변경
- 회원가입 슬랙 메시지 내용 변경
- 결제 슬랙 메시지 내용 변경

RAC-335 refactor : 슬랙 메시지 내용 변경

---

src/main/java/com/postgraduate/global/slack/SlackPaymentMessage.java

RAC-335 refactor : 결제 슬랙 메시지 내용 변경

---

src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminMentoringUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminPaymentUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSalaryUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminSeniorUseCase.java
src/main/java/com/postgraduate/domain/adminssr/application/usecase/AdminUserUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
src/main/java/com/postgraduate/domain/salary/application/usecase/SalaryInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserManageUseCase.java
src/main/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseCase.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyingUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

조회시 트랜잭션 readOnly 설정
조회시 트랜잭션 readOnly 설정

RAC-337 refactor : 조회시 트랜잭션 readOnly 설정

---

src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

기존 프로필 조회로 수정
null을 넘겨주는 것에 대한 프론트의 코드 수정 필요하여 우선 원복
프론트와 상의 후 수정 필요

RAC-337 HotFix : 기존 프로필 조회로 수정

---

src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java

선배 검색시 닉네임 추가
- 회원가입시 Info 값객체 내용 수정
- 업데이트시 Info 값객체 내용 수정

RAC-341 fix : 선배 검색시 닉네임 추가

---

src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Senior.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateService.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java

선배 닉네임 검색 기능 추가 및 오류 수정
- 선배 Info 업데이트 로직 수정
- 선배 닉네임 기반 검색 추가
- 테스트 코드 NPE 수정

RAC-341 fix : 선배 닉네임 검색 기능 추가 및 오류 수정

---

src/main/java/com/postgraduate/domain/mentoring/domain/repository/MentoringDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/salary/application/mapper/SalaryMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCaseTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

몇가지 오류 수정
- 정산 대기/완료 조회시 실제 결제 금액이 아닌, 기존의 20000원 고정 금액이 나오는 부분 수정
- 선배 프로필 미완성시 선배 프로필 조회할 때 이미 작성되어 있는 부분 노출안되는 오류 수정
선배 프로필 수정의 경우 프론트의 수정이 함께 필요함

RAC-341 fix : 몇가지 오류 수정

---

src/main/java/com/postgraduate/domain/mentoring/application/dto/res/AppliedMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/DoneMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/DoneSeniorMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/ExpectedMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/ExpectedSeniorMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/WaitingMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/dto/res/WaitingSeniorMentoringResponse.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCase.java
src/main/java/com/postgraduate/domain/mentoring/presentation/MentoringController.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseCaseTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseCaseTest.java

RAC-341 refactor : 와일드 카드 삭제

---

src/test/java/com/postgraduate/Integration/AuthControllerTest.java
src/test/java/com/postgraduate/Integration/MentoringControllerTest.java
src/test/java/com/postgraduate/Integration/SalaryControllerTest.java
src/test/java/com/postgraduate/Integration/SeniorControllerTest.java
src/test/java/com/postgraduate/Integration/UserControllerTest.java
src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/salary/presentation/SalaryControllerTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
src/test/java/com/postgraduate/domain/user/presentation/UserControllerTest.java
src/test/java/com/postgraduate/support/ControllerTest.java
src/test/java/com/postgraduate/support/IntegrationTest.java
src/test/java/com/postgraduate/support/Resource.java

컨트롤러 단위 테스트 작성
- 각각의 컨트롤러에 대한 단위 테스트 작성
- 통합 테스트 빈 생성 한번에 하도록 변경

RAC-343 test : 컨트롤러 단위 테스트 작성

---

src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/global/config/security/jwt/constant/Type.java
src/main/java/com/postgraduate/global/config/security/jwt/util/JwtUtils.java
src/test/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCaseTest.java

재발급 동시 요청 임시 해결
- 재발급 동시 요청 임시 해결
- 재발급 요청시 2초 동안 기존 재발급 토큰 또한 중복 발급 허용
- 임시 해결로, 추후 변경 예정

RAC-344 fix : 재발급 동시 요청 임시 해결

---

src/main/java/com/postgraduate/global/bizppurio/mapper/BizppurioMapper.java

RAC-336 HotFix : 템플릿 불일치 수정

---

src/main/java/com/postgraduate/global/bizppurio/mapper/BizppurioMapper.java

RAC-336 HotFix : 템플릿 불일치 수정 (선배 회원가입)

---

src/main/java/com/postgraduate/global/bizppurio/mapper/BizppurioMapper.java

RAC-336 HotFix : 템플릿 불일치 수정3

---

src/main/java/com/postgraduate/domain/senior/application/dto/res/SeniorMyPageResponseB.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseCase.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java

CaseB 선배 마이페이지 조회시 인증 상태 포함
인증상태 포함하도록 수정

RAC-342 fix : CaseB 선배 마이페이지 조회시 인증 상태 포함

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignInUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoAccessTokenUseCase.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java
src/main/java/com/postgraduate/domain/auth/presentation/AuthController.java

RAC-342 feat : 케이스 B용 로그인 추가

---

src/main/java/com/postgraduate/global/bizppurio/dto/req/content/button/WebLinkButton.java
src/main/java/com/postgraduate/global/bizppurio/mapper/BizppurioMapper.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAccessDeniedHandler.java
src/main/java/com/postgraduate/global/config/security/jwt/filter/CustomAuthenticationEntryPoint.java

알림톡 내용 수정
- 권한 로그 발생시 접근 경로 로그 추가
- 알림톡 pc_url 추가

RAC-347 fix : 알림톡 내용 수정

---

src/main/java/com/postgraduate/domain/payment/presentation/PaymentController.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java

선배 상세보기 본인계정 여부 오류 수정
certification과 isMine 두개가 서로 위치가 바뀌어서 오류 발생 하는 부분 수정

RAC-347 HotFix : 선배 상세보기 본인계정 여부 오류 수정

---

src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorChangeRequest.java
src/main/java/com/postgraduate/domain/auth/application/dto/req/SeniorSignUpRequest.java
src/main/java/com/postgraduate/domain/mentoring/application/mapper/MentoringMapper.java
src/main/java/com/postgraduate/domain/senior/application/dto/req/SeniorProfileRequest.java
src/main/java/com/postgraduate/domain/senior/application/mapper/SeniorMapper.java
src/main/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseCase.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Info.java
src/main/java/com/postgraduate/domain/senior/domain/entity/Profile.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioJuniorMessage.java
src/main/java/com/postgraduate/global/bizppurio/usecase/BizppurioSeniorMessage.java
src/test/java/com/postgraduate/Integration/AuthControllerTest.java
src/test/java/com/postgraduate/Integration/MentoringControllerTest.java
src/test/java/com/postgraduate/Integration/SalaryControllerTest.java
src/test/java/com/postgraduate/Integration/SeniorControllerTest.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseTypeTest.java
src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyingUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/presentation/MentoringControllerTest.java
src/test/java/com/postgraduate/domain/payment/usecase/PaymentManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java
src/test/java/com/postgraduate/domain/senior/presentation/SeniorControllerTest.java
src/test/java/com/postgraduate/support/Resource.java

회원가입 필수 정보 변경 (chatLink 추가) -> 후배 멘토링 조회시 chatlink안보이는 문제 해결
- 선배 회원가입시 chatLink 필수 추가
- 후배회원 선배로 변경시 chatLink 필수 추가
- 프로필 작성시 chatLink 삭제
- 변경사항 테스트 코드 적용

RAC-353 fix : 회원가입 필수 정보 변경

---

.github/workflows/CI-develop.yml
src/main/java/com/postgraduate/global/config/redis/RedisConfig.java
src/main/java/com/postgraduate/global/config/webclient/WebClientConfig.java
src/test/java/com/postgraduate/Integration/MentoringControllerTest.java

workFlow수정
워크플로우 Redis관련 설정 추가

RAC-373 fix : workFlow수정

---

src/test/java/com/postgraduate/support/IntegrationTest.java

테스트시 슬랙 웹훅 Mock처리
테스트 수행시 슬랙에 알림가지 않도록 수정

RAC-376 test : 테스트시 슬랙 웹훅 Mock처리

---

src/main/resources/templates/seniorCertification.html

사진 크기 고정 및 중앙 정렬
인증 사진 400px 고정 및 테이블 내 삽입

RAC-377 fix : 사진 크기 고정 및 중앙 정렬

---

src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java
src/main/java/com/postgraduate/domain/senior/presentation/SeniorController.java

필드 전체 조회 추가
기존 필드 조회 API 에 전체 조회 추가

RAC-387 feat : 필드 전체 조회 추가

---

src/main/java/com/postgraduate/batch/done/DoneMentoringSkipListener.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryItemWriter.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryJobConfig.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryRepository.java
src/main/java/com/postgraduate/batch/salary/CreateSalarySkipListener.java

배치 처리 관련 로그 추가
- 선배 정산 자동 생성 실패 분석 관련 로그 기능 추가
- 배치 결과 로그 추적 필요

RAC-386 feat : 배치 처리 관련 로그 추가

---

src/main/java/com/postgraduate/global/bizppurio/application/usecase/BizppurioSend.java
src/main/java/com/postgraduate/global/slack/SlackErrorMessage.java

알림톡 발송 실패시 슬랙 알림 추가
- 알림톡 발송 실패시 슬랙에 알림 추가 -> 모든 알림톡 공통 적용

RAC-399 feat : 알림톡 발송 실패시 슬랙 알림 추가

---

src/main/java/com/postgraduate/admin/application/usecase/AdminBatchUseCase.java
src/main/java/com/postgraduate/admin/presentation/AdminWithThymeLeafController.java
src/main/java/com/postgraduate/batch/cancel/CancelJobConfig.java
src/main/java/com/postgraduate/batch/cancel/CancelMentoringSkipListener.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryJobConfig.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryStepListener.java
src/main/resources/templates/adminBatch.html
src/main/resources/templates/adminMain.html

기존 배치 리스너 추가 및 수동 실행 추가
- 정산 배치 처리 결과 관련 리스너 추가
- 멘토링 자동 취소 SkipListener 추가
- 관리자 페이지 배치 수동 실행 추가

RAC-401 feat : 기존 배치 리스너 추가 및 수동 실행 추가

---

src/main/java/com/postgraduate/global/bizppurio/application/dto/req/JuniorMatchingSuccessRequest.java
src/main/java/com/postgraduate/global/bizppurio/application/mapper/BizppurioMapper.java

후배 매칭 성공 알림톡 내용 수정
후배 매칭 성공 알림톡 내용 수정

RAC-405 fix : 후배 매칭 성공 알림톡 내용 수정

---

src/main/java/com/postgraduate/domain/senior/domain/entity/constant/Postgradu.java
src/main/java/com/postgraduate/domain/senior/domain/repository/SeniorDslRepositoryImpl.java

대표 학교 추가
- 카이스트, 고려대학교 추가
- API 요청시 기존의 `~~대` 에서 `~~대학교` 로 수정

RAC-405 feat : 대표 학교 추가

---

src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseCase.java
src/main/java/com/postgraduate/domain/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/domain/service/UserUpdateService.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseTypeTest.java
src/test/java/com/postgraduate/domain/user/domain/service/UserUpdateServiceTest.java

후배 회원 선배 추가 가입시 기본 프로필사진 변경
후배 회원 선배 추가 가입시 기본 프로필 사진 변경
단, 다른 프로필 사진 사용시 프로필 사진 변경 X
- [] 리뷰어 설정했나요?

RAC-411 fix : 후배 회원 선배 추가 가입시 기본 프로필사진 변경

---

src/main/java/com/postgraduate/batch/done/DoneJobConfig.java
src/main/java/com/postgraduate/batch/done/DoneMentoringProcessor.java
src/main/java/com/postgraduate/batch/done/DoneMentoringRepository.java

멘토링 자동완료 로직 수정
ItemReader 쿼리 수정 및 Processor 및 Writer 수정
-> SalaryId 업데이트 (Mentoring Expected상태시 Salary Null로 들어있음

RAC-419 HotFix : 멘토링 자동완료 로직 수정

---

src/main/java/com/postgraduate/batch/done/DoneMentoringRepository.java

RAC-419 fix : 업데이트 쿼리 수정

---

.github/workflows/CI-develop.yml
.github/workflows/CI-prod.yml
build.gradle
src/test/java/com/postgraduate/support/IntegrationTest.java

테스트 코드 h2 데이터베이스 사용 변경
- 테스트 코드 H2 DB사용 변경을 위해, application-test.yml 추가 및 테스트코드 active=test 변경
- githubactions workflow 변경 -> 테스트 빌드시 application-test.yml 사용하도록

RAC-420 refactor : 테스트 코드 h2 데이터베이스 사용 변경

---

src/main/java/com/postgraduate/admin/application/usecase/AdminSalaryUseCase.java

account null 처리
account null 처리 -> 기존 senior null 체크 (오타)

RAC-412 fix : account null 처리

---

src/main/java/com/postgraduate/admin/application/usecase/AdminBatchUseCase.java
src/main/java/com/postgraduate/batch/salary/CreateSalaryJobConfig.java
src/main/java/com/postgraduate/batch/scheduler/JobSchedulerConfig.java
src/main/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseCase.java

배치 수동 실행시 슬랙 알림 삭제
배치 수동 실행시 슬랙 알림 삭제 + 불필요한 로그 삭제 + 배치 시간 변경
변경된 배치 시간에 따른 문제점 유의

RAC-419 fix : 배치 수동 실행시 슬랙 알림 삭제

---

build.gradle
src/main/java/com/postgraduate/domain/auth/application/dto/res/JwtTokenResponse.java
src/main/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseCase.java
src/main/java/com/postgraduate/domain/user/user/application/usecase/UserManageUseCase.java
src/main/java/com/postgraduate/domain/user/user/application/utils/UserUtils.java
src/main/java/com/postgraduate/domain/user/user/domain/entity/User.java
src/main/java/com/postgraduate/domain/user/user/domain/service/UserUpdateService.java
src/main/java/com/postgraduate/domain/user/user/presentation/UserController.java
src/main/java/com/postgraduate/global/bizppurio/application/usecase/BizppurioSend.java
src/main/resources/db/migration/V1_202408230112__alter.sql
src/test/java/com/postgraduate/domain/auth/application/usecase/jwt/JwtUseTypeTest.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/SignUpUseTypeTest.java
src/test/java/com/postgraduate/domain/auth/application/usecase/oauth/kakao/KakaoSignInUseTypeTest.java
src/test/java/com/postgraduate/domain/auth/presentation/AuthControllerTest.java
src/test/java/com/postgraduate/domain/image/application/usecase/ImageUploadUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringApplyingUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringManageUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringSeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/mentoring/application/usecase/MentoringUserInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/payment/usecase/PaymentManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorInfoUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorManageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/application/usecase/SeniorMyPageUseTypeTest.java
src/test/java/com/postgraduate/domain/senior/domain/service/SeniorUpdateServiceTest.java
src/test/java/com/postgraduate/domain/user/application/usecase/UserMyPageUseTypeTest.java
src/test/java/com/postgraduate/domain/user/domain/service/UserGetServiceTest.java
src/test/java/com/postgraduate/domain/user/domain/service/UserUpdateServiceTest.java
src/test/java/com/postgraduate/support/ControllerTest.java
src/test/java/com/postgraduate/support/Resource.java

Flyway 추가
튜토리얼 여부 응답 추가
- Flyway 추가
- User엔티티 테이블 isTutorial 추가 (boolean)
- 기존 로그인 응답 Body -> isTutorial 추가
false의 경우 튜토리얼 진행 필요
true의 경우 튜토리얼 진행 완료

RAC-426 feat : Flyway 추가 + 튜토리얼 여부 응답 추가

---

src/main/java/com/postgraduate/domain/member/user/domain/entity/User.java
src/main/java/com/postgraduate/global/auth/quit/application/usecase/QuitManageUseCase.java

재가입 15일 및 완전탈퇴 30일로 수정
- 재가입 15일 기준 수정
- `User` 클래스 내부 `isHardDelete()` 메소드 추가 -> 완전탈퇴 검사를 위한 30일 경과 측정

RAC-436 fix : 재가입 15일 및 완전탈퇴 30일로 수정

---

src/main/java/com/postgraduate/batch/scheduler/JobSchedulerConfig.java

종료조건 수정, 재시도시 Thread.sleep추가
while문 내부 retries 증가 시키는 로직 수정
재시도시, Job진행 이전 `Thread.sleep(5000)` 추가 -> 5초 대기 후 다시 시도
총 5번까지 시도 가능

RAC-451 fix : 종료조건 수정

---

src/main/resources/db/migration/V1_202408230240__create_quit.sql

HotFix : flyway중간 버전 추가

---

.github/workflows/CD-develop.yml

RAC-478 fix : CD workflow 수정 최종

---

.github/workflows/CD-develop.yml
.github/workflows/CI-develop.yml

RAC-478 fix : CD workflow 수정
